const STATUS={
    APPROVED:"APPROVED",
    REQUESTED:"REQUESTED",
    REJECTED:"REJECTED"
}

const POST_TYPES={
    SELF:"SELF",
    EVENT:"EVENT",
    COLLAB:"COLLAB"
}

const NOTIFICATION_TYPES = {
    GROUP: 'GROUP',
    COLLAB: 'COLLAB'
}

module.exports={
    STATUS,
    POST_TYPES,
    NOTIFICATION_TYPES
}